name: koyamatch.com
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
encoding: utf-8
permalink: math/:categories/:title.html
timezone: Asia/Tokyo